version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "book-store"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-baxecwyq042s"
s3_prefix = "book-store"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
